### ISSUE TITLE
Težave z izračunom dividend

### ISSUE THREAD

**Issue by JakaCikac** [masbug/etoro-edavki#1]
Živjo,

Pri transakcijah, ki so označene kot Rollover Fee in ni podatkov o plačniku pride do napake med izvajanjem programa in sicer KeyError:

`Traceback (most recent call last):
  File davki/bin/etoro-edavki", line 8, in <module>
    sys.exit(main())
  File "davki/lib/python3.7/site-packages/etoro_edavki.py", line 799, in main
    open_pos = openPositions[position_id]
KeyError: 47568XXXX`

Ena taka transakcija je na priloženi sliki. Posledično se tabela ne zgenerira pravilno. Kakšna ideja?

![Screenshot 2021-02-19 at 11 36 09](https://user-images.githubusercontent.com/1460728/108493489-abf48b00-72a6-11eb-8727-0f94f07c7d53.png)

Sicer pa hvala lepa za trud! 
LP

PS: Meni je manjkal `future==0.18.2` v requirements.txt

**Comment by masbug** [comment]
Hvala za report! Sem spregledal tale requirement.
