### ISSUE TITLE
Etoro spremenil strukturo XLS file-a

### ISSUE THREAD

**Issue by dinomne** [masbug/etoro-edavki#10]
Konverter ne dela z trenutnim izvozom etoro account statement-a. V tabeli "Closed Positions" header-i so razlicni od header-a kere aplikacija pricekuje. Updejtam issue-e ko dobim mal casa raziskovat keri headeri so problem

**Comment by masbug** [comment]
Že popravljam :)

**Comment by masbug** [comment]
Popravljeno.
