### ISSUE TITLE
Uvoz v eDavki ne deluje

### ISSUE THREAD

**Issue by sonysunny12** [masbug/etoro-edavki#11]
ob uvozu XML dokumenta eDavki sistem javi napako: Zapis vrste dokumenta (DocumentWorkflowID) ni veljaven. Dovoljeni so zapisi z velikimi črkami. Prosim za pojasnilo/popravek. Hvala, Ivan

**Comment by masbug** [comment]
eDavki imajo več mest za uvoz, ki se različno obnašajo. Predvidevam, da ni šlo pri Doh-Div.xml? To datoteko je potrebno uvoziti na glavnem meniju Dokument->Uvoz.

**Comment by sonysunny12** [comment]
ne, gre za datoteko D-IFI, pri kateri javi to napako v glavnem meniju Dokument - Uvoz.

**Comment by masbug** [comment]
Aha, to pa je potrebno uvozit tako, da greš na D-IFI, izbereš obdobje in "nov prazen dokument". Potem pa je pod "podatki o zavezancu" "Uvoz popisnih listov". Tam izbereš xml in ga uvoziš.

Moram popravit README :)

**Comment by Edenpac** [comment]
Meni javi napako: "Datoteka XML ni pravilne oblike za uvoz."

**Comment by masbug** [comment]
Pravi vnos je na prvi strani: https://github.com/masbug/etoro-edavki?tab=readme-ov-file#uvoz-v-edavke

**Comment by Edenpac** [comment]
Sem poskusil. Tam mi javi pa napako: "Zaradi spremembe obrazca dokumenta ni več mogoče urejati ali oddati. Dokument lahko oddate tako, da izberete oddajo novega dokumenta." . 

Sem poskusil ponovno, vendar mi vedno javi to sporočilo.

**Comment by masbug** [comment]
Pri vseh xmljih javi to?

**Comment by Edenpac** [comment]
Pri IFI in Div. KDVP naloži brez problemov.

**Comment by Edenpac** [comment]
Ne vem kako. Ampak kar naenkrat deluje. Hvala za pomoč

**Comment by masbug** [comment]
2020 so menjali shemo pri D-IFI in Doh-Div...
![image](https://github.com/user-attachments/assets/ef56c827-3909-40eb-9f46-8f0fb57157e5)

To je kar nekaj dela, da bi se zrihtalo še za staro shremo. Kaj pa če probaš vnesit liste za 2019 po starem postopku tj. da greš v D-IFI in daš uvoz popisnih listov? Tudi zavrne xml?

**Comment by Edenpac** [comment]
xml zavrne. Bom pač vsak vpis posebej vpisal. Na srečo jih je samo enih 10.
