### ISSUE TITLE
Skupni Google Sheets dokument

### ISSUE THREAD

**Issue by primozi** [masbug/etoro-edavki#12]
Company_info.xlsx bi bilo morda dobro imeti na Google Docs in ga skupaj urejati? Da ne isce vsak svojih podatkov, ce so morda isti.

**Comment by primozi** [comment]
Tu je moja posodobljena datoteka: [Company_info.xlsx](https://github.com/masbug/etoro-edavki/files/8044801/Company_info.xlsx)
Zaradi kompliciranosti xlsx-a, raje ne delam PR-ja.

**Comment by masbug** [comment]
Merged.

Google Docs se sicer sliši vredu, ampak potem bi bilo to potrebno počrpat v python skripto. Kompromis bi sicer bil kak CSV...
