### ISSUE TITLE
eToro je spremenil vrednosti v polju Type

### ISSUE THREAD

**Issue by jozemlakar** [masbug/etoro-edavki#13]
Skripta pričakuje naslednje tipe:
- Real
- FUT
- CFD
- OPT

V izvozu na včerajšnji dan sem dobil:
- Stocks
- ETF
- Crypto
- CFD

Očitno je, da so Real razdrobili. Vsaj na Stocks, ETF in Crypto. Kako je z ostalimi tipi ne vem. Začasna rešitev je, da si posameznik v svojem izvozu te tri tipe spremeni v Real in skripta deluje normalno.
Prava rešitev pa bi bila, da se podprejo ti trije tipi. Če pa ima kdo čas, naj spodaj zapiše še ostale tipe, ki bi jih srečal.

Lahko pripravim PR.

**Comment by masbug** [comment]
Hvala za opozorilo! Sem skomital popravke in varovalke za morebitne dodatne tipe.
