### ISSUE TITLE
pomoč

### ISSUE THREAD

**Issue by maticcc** [masbug/etoro-edavki#16]
lep pozdrav,
Na spletu sem našel tale program za pretvorbo etoro v edavke. Šel sem po read me postopku, vendar nekaj ne deluje. Prosil bi za kakšen kontakt (mail...), če bi mi lahko odgovorili kaj sem naredil narobe, da mi ne pretvori.

l.p.

**Comment by masbug** [comment]
https://discord.gg/cnRAQ5vg
