### ISSUE TITLE
Napaka pri zagonu etoro_konverzija.cmd

### ISSUE THREAD

**Issue by sonysunny12** [masbug/etoro-edavki#17]
Pozdravljeni,

ob zagonu etoro_konverzija.cmd mi javi spodnjo napako(e). Kaj storiti? Imam namreč nekaj transakcij z ''Commodity'' kot COPPER, URANIUM...je mogoče to in tega ni v seznamu Company info? Kje najti te podatke? Hvala, Ivan

Traceback (most recent call last):
  File "etoro_edavki.py", line 1123, in <module>
  File "etoro_edavki.py", line 269, in main
  File "xml\etree\ElementTree.py", line 1229, in parse
  File "xml\etree\ElementTree.py", line 580, in parse
xml.etree.ElementTree.ParseError: no element found: line 1, column 1671168
[12556] Failed to execute script etoro_edavki
Press any key to continue . . .

**Comment by masbug** [comment]
Živjo,
zagotovo ni na seznamu, bo potrebno dodat.
Kar se pa napake tiče - najbrž so pri eToro spet spremenili statement je potrebno prilagoditi program. Si bom ogledal zadevo čez vikend, pa objavim popravke.

**Comment by SimonVid** [comment]
Ja, so spremenili sheet "Account Activity", kjer so dodali dve koloni:

- kolona Units med Amount in Realized Equity Change
- Asset Type med Position ID in NWA

Če zbrišeš te dve koloni, se skripta uspešno izvede...

Sem poskusil dodati ti dve koloni v definicijo Headerja, vendar pri tem nisem bil uspešen, nisem pa imel dovolj časa, da bi preučil celotno kodo

**Comment by sonysunny12** [comment]
sem zbrisal ti dve koloni ampak javi isto napako, razen column številka je sedaj druga...Dodal sem še dve poziciji v Company info s katerimi so se realizirale transakcije. Ali lahko še vi poskusite izvesti skripto? Prilagam dokumenta [xlxs.]
[Company_info.xlsx](https://github.com/masbug/etoro-edavki/files/10402325/Company_info.xlsx)
[etoro.xlsx](https://github.com/masbug/etoro-edavki/files/10402329/etoro.xlsx)

Traceback (most recent call last):
  File "etoro_edavki.py", line 1123, in <module>
  File "etoro_edavki.py", line 269, in main
  File "xml\etree\ElementTree.py", line 1229, in parse
  File "xml\etree\ElementTree.py", line 580, in parse
xml.etree.ElementTree.ParseError: unclosed token: line 1, column 1335278
[7820] Failed to execute script etoro_edavki
Press any key to continue . . .

**Comment by SimonVid** [comment]
Jaz nisem avtor skripte, sem samo podal info za razvijalca, kaj sem jaz naredil, da ni bilo več napake... Očitno je moj etoro file  bolj standarden :-)

**Comment by SimonVid** [comment]
Sem pa pognal skripto na vaših datotekah in je zaključila brez napake. Upam, da so podatki testni...

**Comment by SimonVid** [comment]
Sporočim jutri, imam na drugem računalniku

**Comment by SimonVid** [comment]
Uporabljam 1.4, Doh-Div je izdelan, samo je bila moja DŠ noter...

[Doh-Div.txt](https://github.com/masbug/etoro-edavki/files/10409919/Doh-Div.txt)

**Comment by masbug** [comment]
Dodal sem popravke. Prenesite si verzijo 1.5.
Osebne podatke bom pobrisal, da jih ne poberejo razni crawlerji...

**Comment by sonysunny12** [comment]
Zdravo,

tudi z novo verzijo 1.5 mi javi tole napako. Zbrisal sem tista dva stolpca pa je isto....a lahko še vi probate?

Traceback (most recent call last):
  File "etoro_edavki.py", line 1105, in <module>
  File "etoro_edavki.py", line 258, in main
  File "xml\etree\ElementTree.py", line 1229, in parse
  File "xml\etree\ElementTree.py", line 580, in parse
xml.etree.ElementTree.ParseError: unclosed token: line 1, column 5300204
[16228] Failed to execute script etoro_edavki
Press any key to continue . . .
[Company_info.xlsx](https://github.com/masbug/etoro-edavki/files/10420247/Company_info.xlsx)
[etoro.xlsx](https://github.com/masbug/etoro-edavki/files/10420248/etoro.xlsx)

davčna 60835524
