### ISSUE TITLE
napaka pri zagonu etoro konverzija 2

### ISSUE THREAD

**Issue by sonysunny12** [masbug/etoro-edavki#18]
Zdravo,

tudi z novo verzijo 1.5 mi javi tole napako. Zbrisal sem tista dva stolpca pa je isto....a lahko še vi probate?

Traceback (most recent call last):
File "etoro_edavki.py", line 1105, in
File "etoro_edavki.py", line 258, in main
File "xml\etree\ElementTree.py", line 1229, in parse
File "xml\etree\ElementTree.py", line 580, in parse
xml.etree.ElementTree.ParseError: unclosed token: line 1, column 5300204
[16228] Failed to execute script etoro_edavki
Press any key to continue . . .

**Comment by masbug** [comment]
Stolpca sedaj morata biti. Zgleda kot, da vaš firewall blokira download datoteke z menjalnimi tečaji.
Se vam ustvari datoteka bsrate-2023114.xml v mapi?

V prilogi je današnja. Samo razpakirajte v isto mapo kjer je program.
[bsrate-2023115.zip](https://github.com/masbug/etoro-edavki/files/10420812/bsrate-2023115.zip)

**Comment by sonysunny12** [comment]
datoteka bsrate je bila ustvarjena.....s tole poslano pa je sedaj izvedlo skripto....žal pa je datoteka Doh-Div še vedno v xml namesto v csv in je v edavke ne morem uvoziti tudi če naredim konverzijo xml=>csv prek spleta..

**Comment by masbug** [comment]
V eDavke uvozite xml za Doh-Div tukaj: https://edavki.durs.si/EdavkiPortal/PersonalPortal/CommonPages/Documents/Import.aspx
Se pravi Namizje->Dokumenti->Uvoz. To je tudi razlog zakaj je potrebno vnesti davčno št.
![image](https://user-images.githubusercontent.com/11191264/213861294-584066b9-5d9a-4192-b4c4-da0709fc50d0.png)


Druga dva xmlja se pa uvozita na namenskih straneh za Doh-KDPV in D-IFI.
