### ISSUE TITLE
Doh-Div - Polje 'Vrsta dokumenta' mora biti obvezno izpolnjeno.

### ISSUE THREAD

**Issue by primozi** [masbug/etoro-edavki#2]
Uvoz generiranega xml-ja ne deluje. Vrne napako:
Polje 'Vrsta dokumenta' mora biti obvezno izpolnjeno.

**Comment by masbug** [comment]
Hvala za report. Sem skomital fix 7ea45b2d1b9065de4227a27541612c3efcf35e4e, vendar ga ne morem preverit, ker sem napoved že oddal...

**Comment by masbug** [comment]
Sem preveril pri kolegu, deluje.
