### ISSUE TITLE
Težava doh-div

### ISSUE THREAD

**Issue by topmiha** [masbug/etoro-edavki#22]
Pozdravljeni,

prosim za pomoč, ko poskušam uvoziti doh-div.xml v edavke mi javi kritične vsebinske napake - datoteka ni pravilne oblike. Ima kdo podobne težave ter obstaja rešitev?

Hvala in lep pozdrav,
Miha

**Comment by masbug** [comment]
Živjo, pomoje je problem napačno mesto uvoza.
Doh-div je potrebno uvoziti tukaj:
[](https://github.com/masbug/etoro-edavki/issues/18#issuecomment-1399217980)

**Comment by topmiha** [comment]
Hvala.
