### ISSUE TITLE
Doh-Div

### ISSUE THREAD

**Issue by gaber444** [masbug/etoro-edavki#23]
Pri uvozu v edavke, za obrazec Doh-Div sporoči napako Dartoteka ni pravilne oblike. Z Doh-KDVP in D-IFI so pa edavki
zdovolnji. Mogoče sem jaz kaj spregledal ali se je mogoče kaj obrazec za Doh-Div spremenil.

**Comment by SimonVid** [comment]
https://github.com/masbug/etoro-edavki/issues/22

**Comment by gaber444** [comment]
hvala
