### ISSUE TITLE
DohDiv - Zneski tujega plačanega davka ter členi oprostitve

### ISSUE THREAD

**Issue by damir-dezeljin** [masbug/etoro-edavki#24]
`README.md` navaja, da eTorov letni Excelov izvoz prometa ne vključuje podatka o plačanem tujem davku od dividend:
> Prav tako eToro v poročilu ne zapiše odvedenega davka od dividend (witholding tax), za katerega lahko uveljavljamo olajšavo. 
> Izpisek plačanega davka od dividend lahko zahtevate od eToro preko supporta.

Sprašujem, če gre tu za star tekst, ki ni več relevanten? Namreč, če prav razumem moj lanski oddan DohDiv (za leto 2021), kakor tudi letošnji (2022), ki sem ju naredil s tem programom (še enkrat hvala za odlično delo), pri posameznem vnosu vključujejo `Tuji davek***`.

Prav tako mi je eTorova podpora sporočila:
> ...
> We would like to clarify that all rollover fees and dividend payments with the tax deducted on them are shown in your account statement.
>
> Whenever you wish to check any transaction in your account, you may check your account statement. Dividends can be found in the dividend section of the Account Statement. To access your account statement please click on the following link:  https://www.etoro.com/customer-service/help/70325632/where-is-my-account-statement/
> ...

Tako me zanima, če moram kaj narediti glede samega zneska davka?

Vesel bom te informacije, da bom bolje razumel.

Dodatno je v `README.md` navedeno:
> Pri uveljavljanju olajšave za že odvedeni davek v tujini, je potrebno na eDavkih specificirati mednarodno pogodbo od preprečevanju dvojnega obdavčevanja in člen. Za pomoč pri pogodbah je tabela:

^^^
Glede tega me zanima, če prav razumem, da za vsako delnico iz  npr. US se skopira relevanten člen za ZDA (povsod isti), prav tako za vsako delnico GB se skopira relevanten člen za Združeno kraljevstvo (povsod isti, verjetno tudi za UK). Če je temu tako, zakaj ne bi te člene po državah uporabnik kar vpisal v konfiguracijsko datoteko in bi jih program dodal v generiran XML?

Hvala za kodo in ves trud, ki ga vlagate v to.

**Comment by masbug** [comment]
> Sprašujem, če gre tu za star tekst, ki ni več relevanten? Namreč, če prav razumem moj lanski oddan DohDiv (za leto 2021), kakor tudi letošnji (2022), ki sem ju naredil s tem programom (še enkrat hvala za odlično delo), pri posameznem vnosu vključujejo `Tuji davek***`.

Ja, tisto je star tekst. Bo treba popravit README. Pri prvi verziji statementa tega še ni bilo.

> Tako me zanima, če moram kaj narediti glede samega zneska davka?

Ne.

> ^^^ Glede tega me zanima, če prav razumem, da za vsako delnico iz npr. US se skopira relevanten člen za ZDA (povsod isti), prav tako za vsako delnico GB se skopira relevanten člen za Združeno kraljevstvo (povsod isti, verjetno tudi za UK).

Tako imajo napisano pri FURSu... a je to v resnici potrebno ali ne ne vem. Jaz polja pustim prazna, pa me doslej še niso klicali na zagovor...priložim pa eToro statement, ki vsebuje samo tabelo dividend.

> Če je temu tako, zakaj ne bi te člene po državah uporabnik kar vpisal v konfiguracijsko datoteko in bi jih program dodal v generiran XML?

Se strinjam. Ampak jih je ogromno za poiskat.
