### ISSUE TITLE
Error:  HeadersNotFound: Header column not found on sheet 'Closed Positions'

### ISSUE THREAD

**Issue by Draskec90** [masbug/etoro-edavki#25]
Hej,

ob zagonu mi javi to napako. Bi mi kdo vedel pomagat oziroma bi lahko dobil kaki kontakt na koga se lahko obrnem? Najlepša hvala. LP, M
 
Traceback (most recent call last):
  File "etoro_edavki.py", line 1132, in <module>
  File "etoro_edavki.py", line 310, in main
  File "openpyxl_templates\table_sheet\table_sheet.py", line 379, in read
openpyxl_templates.table_sheet.table_sheet.HeadersNotFound: Header column not found on sheet 'Closed Positions' either make sure that the following headers are present 'Position ID, Action, Amount, Units, Open Date, Close Date, Leverage, Spread, Profit, Open Rate, Close Rate, Take profit rate, Stop lose rate, Rollover Fees and Dividends, Copied From, Type, ISIN, Notes'.
[24144] Failed to execute script etoro_edavki

**Comment by Ocepek-Domen** [comment]
V list "Closed Positions" so dodali oz. preimenovali polja "Spread Fees (USD)", "Profit(USD)", "Profit(EUR)";
ter v list "Dividends": "Net Dividend Received (EUR)", "Withholding Tax Amount (EUR)"
Te spremembe povzročajo težavo. 
Začasno lahko preimenuješ oz. izbrišeš.

**Comment by masbug** [comment]
Urejeno.
