### ISSUE TITLE
Verzija Python-a

### ISSUE THREAD

**Issue by SimonVid** [masbug/etoro-edavki#26]
Tole je bolj za requirements del :-). Za uporabo skripte je obvezen Python 3.9, pri višjih verzijah pride do določenih nekompatibilnosti z modulom collections (cannot import name 'Iterable' from 'collections').

**Comment by AndrazTom** [comment]
Nekateri witholding tax rate-i so podani v "floatih" npr. 20.41% ne 20 % (vsaj pri meni)
trenutno line 894 oz. definicija witholding_tax_rate

Fix: 

withholding_tax_rate = (
                float(xlsDividend.withholding_tax_rate.rstrip("%")) / 100
            )

**Comment by masbug** [comment]
Popravljeno, da dela tudi z višjimi verzijami. 5fa79024a221e1bbbf03a13a0efde8d626d5c8a8
