### ISSUE TITLE
Napacen izracun witholding tax rate.

### ISSUE THREAD

**Issue by AndrazTom** [masbug/etoro-edavki#27]
Nekateri witholding tax rate-i so podani v "floatih" npr. 20.41% ne 20 % (vsaj pri meni)
trenutno line 894 oz. definicija witholding_tax_rate

Fix:

withholding_tax_rate = (
float(xlsDividend.withholding_tax_rate.rstrip("%")) / 100
)

**Comment by andrej-taranenko** [comment]
Tudi pri meni, kjer je v etorro statement witholding tax rate 20.42 % (ostala realna števila so z decimalno vejico, ta je s piko - mogoče je to težava?). Posledično skripta nekaj narobe izračuna in dobim negativne dividene.

**Comment by masbug** [comment]
Popravljeno z 1.6.1.
