### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bombica** [masbug/etoro-edavki#28]
Pri konverziji podatkov za leto 2022 se zgodi napaka. Priprava podatkov za leto 2021 in 2023 lepo deluje.
Klic:
./etoro-edavki -y 2022 etoroAccountStatement-2022.xlsx
Napaka:

| eToro->eDavki | verzija 1.6.0

Traceback (most recent call last):
  File ".../Library/Python/3.9/bin/./etoro-edavki", line 8, in <module>
    sys.exit(main())
  File ".../Library/Python/3.9/lib/python/site-packages/etoro_edavki.py", line 334, in main
    positionSymbols = get_position_symbols(transactionList)
  File ".../Library/Python/3.9/lib/python/site-packages/etoro_edavki.py", line 172, in get_position_symbols
    if xlsTransaction.position_id is None or xlsTransaction.details.find("/") < 0:
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by masbug** [comment]
Poskusite izvozit za daljše obdobje. Program izhodne podatke vedno pripravi za izbrano leto.

**Comment by bombica** [comment]
Pripravil sem XLSX izvoz za celotno obdobje, to je od 1.1.2009 do danes.
Napaka je enaka.

CODEMONKEE d.o.o., Ljubljanska cesta 24b, 4000 Kranj, Slovenia
T: +386 (0) 41 654 525 | E: ***@***.*** ***@***.***> | W: www.codemonkee.si <http://www.codemonkee.si/>

**Comment by masbug** [comment]
Zgleda, da je nek problem v "Account Activity" tabeli, stolpec "Details". Potrebujem export te tabele. Zanimajo me pa Date, Type in Details stolpci.

**Comment by bombica** [comment]
[etoro-account-statement-1-1-2022-12-31-2022_export.xlsx](https://github.com/masbug/etoro-edavki/files/13980622/etoro-account-statement-1-1-2022-12-31-2022_export.xlsx)

**Comment by masbug** [comment]
Ok, vidim problem. 2 polja imata čisto prazen "Details"
![image](https://github.com/masbug/etoro-edavki/assets/11191264/ec020840-2435-4787-9a7c-ba8aa34cf53d)
Quick fix je, da samo vpišete karkoli v ti dve polji. Bom pa še skomital popravek.

**Comment by bombica** [comment]
Enkratno :)
Moja Company_info datoteka ima že 334 zapisov.
Kako jo lahko delim z ostalimi?

**Comment by masbug** [comment]
Lahko kar sem, pa bom dodal v skupno.

**Comment by bombica** [comment]
[Company_info.xlsx](https://github.com/masbug/etoro-edavki/files/13986072/Company_info.xlsx)

**Comment by bombica** [comment]
Pa še informacije glede specificiranja mednarodnih pogodb preprečevanje dvojnega obdavčenja v eDavkih.
Na FURSu so mi dali pojasnilo, da tega podatka ni potrebno izpolniti.

**Comment by masbug** [comment]
Hvala!

**Comment by Vladi007** [comment]
Kaj pa priložite kot dokazilo o plačilu tujega davka?

**Comment by masbug** [comment]
Jaz priložim kar etoro statement.

**Comment by bombica** [comment]
> Jaz priložim kar etoro statement.

Tudi jaz :)

**Comment by Vladi007** [comment]
ok, hvala za info!

**Comment by bombica** [comment]
Živjo, ponovno sem dodal nekaj podjetij :)
lp

[Company_info.xlsx](https://github.com/user-attachments/files/18854455/Company_info.xlsx)
