### ISSUE TITLE
Prazen <edp:Header>

### ISSUE THREAD

**Issue by bombica** [masbug/etoro-edavki#29]
Pri pripravi datotek D-IFI.xml in Doh-KDVP.xml so podatki v <edp:Header> prazni, kar povzroči napako pri uvozu dokuementa v eDavke.
Vsebina:
<edp:Header>
	<edp:taxpayer/>
</edp:Header>
Pri datoteki Doh-Div.xml se podatki pravilno napolnijo.

**Comment by masbug** [comment]
Popravljeno.
