### ISSUE TITLE
D-IFI število decimalk

### ISSUE THREAD

**Issue by bombica** [masbug/etoro-edavki#30]
Število decimalnih mest bi bilo potrebno v datoteki D-IFI povečati iz 4 na 6, saj eToro uporablja pri vrednostih v stolpcu Units 6 decimalk, kar lahko povzroči, da je podatek v datoteki D-IFI 0,000, na primer:
<img width="607" alt="image" src="https://github.com/masbug/etoro-edavki/assets/4738282/fbcdf4d5-018c-46f2-a6bf-6bd41e392837">

To kasneje povzroči sledečo težavo pri oddaji v eDavke:
<img width="1185" alt="image" src="https://github.com/masbug/etoro-edavki/assets/4738282/5bd67039-a3fa-4b4e-b27c-5dc8608c7b8e">

eDavki omogočajo vnos podatka na 22 decimalk natančno.

**Comment by masbug** [comment]
Popravljeno.
