### ISSUE TITLE
Predolg podatek ...KDVPItem.Securities.Code

### ISSUE THREAD

**Issue by bombica** [masbug/etoro-edavki#31]
V datoteki Doh-KDVP je potrebno skrajšati podatek ...KDVPItem.Securities.Code na 10 mest, ker je takšna tudi omejitev XML sheme za oznako vrednostnega papirja v sistemu eDavki.

https://edavki.durs.si/Documents/Schemas/Doh_KDVP_9.xsd

<xs:simpleType name="typeKDVPItemCode">
  <xs:restriction base="xs:string">
    <xs:maxLength value="10"/>
  </xs:restriction>
</xs:simpleType>

Napaka, ki se namreč zgodi pri uvozu je na primer takale:

<img width="693" alt="image" src="https://github.com/masbug/etoro-edavki/assets/4738282/8d2db7d5-13b2-4b4c-8e97-c87feadb0941">

**Comment by masbug** [comment]
Popravljeno.
