### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by LeMar70** [masbug/etoro-edavki#33]
Mi lahko kdo pomaga.  
ob zagonu komande
 etoro-edavki etoroaccountstatement2023.xlsx
mi ob izvajanju javi napako..
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

Kje je tezava.. Hvala

**Comment by masbug** [comment]
Hm, zgleda kot da je nek problem s certifikatom pri downloadu https://www.bsi.si/_data/tecajnice/dtecbs-l.xml
...če nimate precej starih windowsov, potem za vsak slučaj preverite računalnik za viruse (potencialni [man-in-the-middle attack](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)).

Hitra rešitev je, da ročno prenesete https://www.bsi.si/_data/tecajnice/dtecbs-l.xml in shranite kot bsrate-<leto><mesec><dan>.xml. Primer za danes: bsrate-2024125.xml
To datoteko skopirate v isto mapo kot je etoro_edavki.exe. Potem bi moralo delovati. Če ne bo, pa priporočam, da vse skupaj ponovno prenesete na drugem računalniku in tam tudi poženete.

**Comment by LeMar70** [comment]
Hvala za pomoc. 
Te napake ni več. se mi pa pojavi nova, ki pa naj bi bila odpravljena.
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/openpyxl_templates/table_sheet/table_sheet.py", line 379, in read
    raise HeadersNotFound(self)
openpyxl_templates.table_sheet.table_sheet.HeadersNotFound: Header column not found on sheet 'Closed Positions' either make sure that the following headers are present 'Position ID, Action, Amount, Units, Open Date, Close Date, Leverage, Spread Fees (USD), Profit(USD), Profit(EUR), Open Rate, Close Rate, Take profit rate, Stop lose rate, Rollover Fees and Dividends, Copied From, Type, ISIN, Notes'.

Skripto zaganjam na mac.u. 

hvala za pomoc.

**Comment by masbug** [comment]
A pa tako poimenovani stolpci obstajajo v vašem xlsu na strani "Closed Positions"?

**Comment by LeMar70** [comment]
Ja sem preveril. Samo se mi skripta ne izvede.  Lahko vam pošljem xlsx. 

Če lahko pomagate.
Hvala

**Comment by masbug** [comment]
Lahko, pošljite.

**Comment by LeMar70** [comment]
￼

Hvala

**Comment by masbug** [comment]
...potrebujem xlsx datoteko.

**Comment by LeMar70** [comment]
Sem jo pripel.   Vam jo lahko pošljem na kak drug način.

**Comment by LeMar70** [comment]
[etoro-account-statement-1-1-2023-12-31-2023.xlsx](https://github.com/masbug/etoro-edavki/files/14061124/etoro-account-statement-1-1-2023-12-31-2023.xlsx)

**Comment by masbug** [comment]
Pošljite mi še davčno številko na mitja.spes@gmail.com
