### ISSUE TITLE
Doh-Div - napaka pri uvozu na edavke

### ISSUE THREAD

**Issue by Vladi007** [masbug/etoro-edavki#34]
E-davki pri uvozu Doh-Div javijo spodnjo napako:

Kritične vsebinske napake:
• Datoteka ni pravilne oblike.

Ima še kdo s tem težave?

**Comment by masbug** [comment]
Uvoženo pa je bilo tukaj? ![](https://user-images.githubusercontent.com/11191264/221360416-bce47565-7f11-4d5e-a3e2-4466785c1bc7.png)

**Comment by Vladi007** [comment]
Uvoženo je bilo direktno iz obrazca Doh-Div. Sem pa ravno ob kreiranju tega print screena opazil, da naj bi šlo tukaj za uvoz iz .csv datoteke. Uvoz iz glavnega menija deluje. Najlepša hvala za info!

![Zajeta slika](https://github.com/masbug/etoro-edavki/assets/17086760/beb26d62-31a1-4135-9a50-7355a85c2f42)
