### ISSUE TITLE
import težava

### ISSUE THREAD

**Issue by markomik515** [masbug/etoro-edavki#35]
Zdravo,

Ko skušam generirati poročila z "etoro-edavki -y 2023 account_statement_2023.xlsx" mi javi spodnjo težavo. Imate kakšen pointer, kaj počnem narobe oz. kaj lahko poskusim narediti?

![slika](https://github.com/masbug/etoro-edavki/assets/76162220/f98c55bd-7aa5-44ac-8b8c-7f791c57c77a)

**Comment by masbug** [comment]
Zgleda kot stara aplikacija, ki ne deluje več. Prenesite zadnjo verzijo.
