### ISSUE TITLE
težava pri pogonu prevedene skripte

### ISSUE THREAD

**Issue by Mihajlo1250** [masbug/etoro-edavki#36]
Pozdravljeni.

V cmd sem po zagonu etoro_konverzija prejel tole obvestilo:
...
Traceback (most recent call last):
  File "etoro_edavki.py", line 1169, in <module>
  File "etoro_edavki.py", line 322, in main
  File "openpyxl_templates\table_sheet\table_sheet.py", line 379, in read
openpyxl_templates.table_sheet.table_sheet.HeadersNotFound: Header column not found on sheet 'Closed Positions' either make sure that the following headers are present 'Position ID, Action, Amount, Units, Open Date, Close Date, Leverage, Spread Fees (USD), Market Spread (USD), Profit(USD), Profit(EUR), Open Rate, Close Rate, Take profit rate, Stop lose rate, Rollover Fees and Dividends, Copied From, Type, ISIN, Notes'.
[13624] Failed to execute script 'etoro_edavki' due to unhandled exception!
Press any key to continue . . .

Kaj bi lahko bilo narobe?
(predhodno sem v mapo skopiral etoro.xlsx, v cmd sem vpisal DŠ in kratico FO)

**Comment by masbug** [comment]
Vzrok je stara verzija programa ali pa star statement export.

**Comment by Mihajlo1250** [comment]
Ko sem javil napako, sem:
-uporabil najnovejšo verzijo programa (1.6.4).
-uporabil account statement za "last year", torej 01/01/2023 - 31/12/2023.

Tokrat sem:
-kot izvozil account statement 01/01/2023 -  01/01/2024
- skopiral lansko datoteko taxpayer.xml (ki izgleda enaka kot tista, ki jo je skripta v prejšnjem poskusu kreirala sama z vprašanji)
Kaj od tega je odpravilo napako, ne vem.

Hvala za odzivnost.
Zanima me, ali lahko prispevam s svojimi podatki v skupno bazo Company_info?
LP

**Comment by masbug** [comment]
Precej čudno. Bi lahko videl header tabele "Closed positions"?

Company info lahko kar dodate tukaj v komentar, pa bom združil v skupnega.

**Comment by Mihajlo1250** [comment]
[Header of Closed positions.xlsx](https://github.com/masbug/etoro-edavki/files/14318206/Header.of.Closed.positions.xlsx)


To je xlsx prejšnje datoteke etoro.xlsx (Last year) z zgornjo vrstico zavihka 'Closed positions'; v originalu je v vseh stolpcih na tej vrstici vklopljen tudi 'sort filter' gumb.

Ko končam z dopolnjevanjem Company info, pošljem.

**Comment by masbug** [comment]
Star etoro export je... manjkajo stolpci. Samo v januarju so ~3x spremenili kako izgleda export.
![image](https://github.com/masbug/etoro-edavki/assets/11191264/17a8c960-b3bc-4700-be2e-805a55bf94ec)

**Comment by Mihajlo1250** [comment]
Če so res spreminjali, potem je res to razlog. Moj "nedelujoči" export je s 3. januarja. Hvala za diagnozo.

**Comment by Mihajlo1250** [comment]
Pošiljam podatke za Company info, ki sem jih dodal k manjkajočim.

[company_info-additional.xlsx](https://github.com/masbug/etoro-edavki/files/14324736/company_info-additional.xlsx)

Ponovno hvala za vaš trud in čas.
