### ISSUE TITLE
tečaj usd-eur IFI

### ISSUE THREAD

**Issue by kure87** [masbug/etoro-edavki#37]
Super skripta, zelo olajša delo. 

Me pa nekaj zanima ali je napaka v skripti ali pa jaz nekaj ne razumem. 
Pri izračunu IFI in preračunu vrednosti enote iz USD v EUR, kako se obračuna vrednost enote v EUR? Vrednost enote USD / tečaj BS na dan prodaje? Kako je potem mogoče, da je za eno prodajo IFI (isti IFI, samo v večih delih -  več oprtih pozicij) drugačna vrednost enote v EUR na vsaki poziciji, čeprav je vrednost enote v USD v eToro izpisku pri vsaki poziciji identična?

Debug excel - Derivate (long) [dodan stolpec Trade price (USD) - samo za prikaz USD cene v eToro izpisku]
<img width="263" alt="ifi" src="https://github.com/masbug/etoro-edavki/assets/17985639/d365befa-b9ff-47a7-96ad-3c87e9831c36">

4 pozicije so prodane istočasno, v eToro izpisku je vrednost enote v USD pri vseh enaka. Izračunana vrednost na enoto v EUR pa ima vsaka pozicija drugačno. Sicer res gre za decimalke ampak vseeno. 

Že vnaprej hvala za odgovor.

**Comment by masbug** [comment]
> Pri izračunu IFI in preračunu vrednosti enote iz USD v EUR, kako se obračuna vrednost enote v EUR? Vrednost enote USD / tečaj BS na dan prodaje?
Obračuna se na menjalno vrednost USD <-> EUR na dan prodaje (bsrate-2024213.xml). Za dani primer 28.2.2023 je 1 EUR bil vreden 1.0619 USD.

>Kako je potem mogoče, da je za eno prodajo IFI (isti IFI, samo v večih delih - več oprtih pozicij) drugačna vrednost enote v EUR na vsaki poziciji, čeprav je vrednost enote v USD v eToro izpisku pri vsaki poziciji identična?
Nekaj zagotovo prispevajo zaokrožitve pri eToro izpisu. Zakaj se pa razlikujejo posamezne pozicije je pa najbrž razlika v quantity/units. Mogoče skopirate te vrstice iz statementa, pa bo lažje pojasniti razliko.

**Comment by kure87** [comment]
Kateri del statement-a? Closed positions?

**Comment by masbug** [comment]
Closed positions. Potrebujem samo tiste 4 pozicije.
Lahko tudi tukaj: https://discord.gg/H3P2BVpQ
