### ISSUE TITLE
ImportError: cannot import name 'save_virtual_workbook' from 'openpyxl.writer.excel'

### ISSUE THREAD

**Issue by Wick96** [masbug/etoro-edavki#38]
Pozdravljeni,
pri poganjanju programa naletim na spodnji error:

![slika](https://github.com/masbug/etoro-edavki/assets/14943797/820a99b7-517c-4ee4-aa67-433c1780ca9c)

Sistem: MacOS 14.3.1
Python Ver: Python 3.9.6
Pip Ver: pip 24.0 from (python 3.9)

**Comment by Wick96** [comment]
Ista napaka tudi če dodam file.
![slika](https://github.com/masbug/etoro-edavki/assets/14943797/b2ef2729-08b0-4796-afed-9a0c4d3a6ade)

**Comment by Wick96** [comment]
Dodajam še pip3 pakete:
![slika](https://github.com/masbug/etoro-edavki/assets/14943797/c34d1a7c-ae79-4ba7-90af-2a4f1d095e50)

**Comment by Wick96** [comment]
Težavo reši tole:
`pip3 install openpyxl==3.0.10`

Ampak v prihodnje bi bilo mogoče dobro narediti rewrite kode, ki uporablja to zadevo, da bo delovala tudi na verziji 3.1.*

**Comment by masbug** [comment]
Je že tako... https://github.com/masbug/etoro-edavki/blob/main/requirements.txt
