### ISSUE TITLE
Sprememba leta poročila

### ISSUE THREAD

**Issue by miha-jumper** [masbug/etoro-edavki#42]
Živjo,

Želim oddati poročilo za pretekli 2 leti. Za 2023 mi poročila generira normalno, za 2022 pa dobim prazne (ker ne znam nastavit na 2022)

Ali obstaja enostaven način kako spremeniti leto pročila brez pythona? Če ne, bi pa prosil za enostaven screenshot iz pythona, pa bom našel nekoga da zrihta :)

**Comment by masbug** [comment]
Živjo, leto lahko spremeniš s parametrom "-y 2022".

![image](https://github.com/user-attachments/assets/3930d78b-6d3f-420f-b52e-dc984b3ce87f)

**Comment by masbug** [comment]
Lahko odpreš cmd.exe in navigiraš v mapo na sliki. Recimo da je ta mapa d:\edavki
V cmd.exe potem napišeš (vrstica za vrstico):
d:
cd edavki
etoro_edavki.exe -y 2022 etoro-edavki-2022.xlsx
----------------------

Opcija 2 pa je, da skopiraš etoro_konverzija.cmd, datoteko odpreš z recimo notepadom in spremeniš vrstico:
etoro_edavki.exe etoro.xlsx
v
etoro_edavki.exe -y 2022 etoro-edavki-2022.xlsx
