### ISSUE TITLE
Doh-Div Dokazilo o plačilu tujega davka

### ISSUE THREAD

**Issue by Edenpac** [masbug/etoro-edavki#44]
Pri oddajanju poročila za dividende, mi javi kritično napako, da potrebujem dokazilo o plačilu tujega davka. Kako dobim to?

**Comment by masbug** [comment]
Jaz priložim kar etoro xlsx.

**Comment by Edenpac** [comment]
Kaj izvoziš iz etorota samo za tisto leto? Ali odstraniš kripto vnose? Še kaj spreminjaš datoteko?

**Comment by masbug** [comment]
Samo za tisto leto. Ničesar ne odstranim ali spreminjam. FURS dobi mimo tebe vse podatke o tvojih pozitivnih tradih (ne pa negativnih). Kripto, če ne uporabljaš leverage, ne pade pod D-IFI in si oproščen, če tega ne delaš kot s.p. Crypto margin pa ne vem, ta bi pomoje moral past pod D-IFI, ampak je za vprašat na FURS-u.
