### ISSUE TITLE
Samoprijava za prejšnja leta (2019-2023)

### ISSUE THREAD

**Issue by sonysunny12** [masbug/etoro-edavki#45]
Pozdravljeni,

uporabil sem zadnji verziji 1.7.1 in v output xml datotekah se avtomatsko pojavi obdobje preteklega leta, čeprav recimo rabim za 2019, 2020, 2021, 2022 in 2023. Ali to lahko potem ročno popravljam kot txt datoteko recimo? Hvala! Ivan

**Comment by sonysunny12** [comment]
spremenil sem obdobja v xml dokumentih ampak kolikor vidim so prazni, ni zapisov. Ali se v tem primeru sploh kaj lahko odda? v edavkih mi zahteva vsaj en zapis...in praznega niti ne morem oddat, Doh Div pa je spremenjen obrazec in ga zavrača.
Kako sploh kaj oddati potem za 2019? 
[etoro.xlsx](https://github.com/user-attachments/files/17608201/etoro.xlsx)

**Comment by sonysunny12** [comment]
Za 2023 mi noče uvoziti xml KDVP in Doh Div....čeprav so zapisi notri....pri KDVP se enostavno nič ne zgodi...ni povratne info sploh...pri Doh Div javi, da xml ni pravilne oblike....tudi če grem prek direkt uvoza...Doh IFI mi je normalno uvozil... v čem je težava? lp
[etoro.xlsx](https://github.com/user-attachments/files/17611643/etoro.xlsx)
[Company_info.xlsx](https://github.com/user-attachments/files/17611647/Company_info.xlsx)

**Comment by masbug** [comment]
Po defaultu program vedno v output zapiše xml datoteke za preteklo leto. Za poljubno leto je potrebno dodat ```-y <letnica>```. etoro.xlsx pa mora vsebovati podatke za tisto leto (ali več).

1. Najprej izvoz etoro statementa vsaj za leta, ki vas zanimajo. Npr. od 1.1.2018 do danes in shranite kot etoro.xlsx v mapo kjer je ta program.
2. Odprete cmd.
3. V cmd se premaknete v pravo mapo: cd <mapa kjer je program in etoro.xlsx>
4. Poženete pretvorbo za izbrano leto: ```etoro_edavki.exe -y 2019 etoro.xlsx```
5. Preimenujete mapo output v recimo 2019.
6. Poženete pretvorbo za naslednje leto: ```etoro_edavki.exe -y 2020 etoro.xlsx``` in preimenujete output v 2020...
7. ...

Če podatkov v xmlu ni, potem najbrž določenega tipa transakcij niste opravljali...npr. KDVP se uporablja samo za delnice brez vzvoda...po novem je tako vse CFD, kar gre v D-IFI. Dividende gredo pa v Doh-Div.
[Vse xmlje se uvozi na vhodni strani v edavkih](https://user-images.githubusercontent.com/11191264/221360416-bce47565-7f11-4d5e-a3e2-4466785c1bc7.png)

**Comment by masbug** [comment]
Mogoče bo potrebno spremenit še tole po vseh xmljih. "I" pomeni samoprijava.
```
<edp:DocumentWorkflowID>O</edp:DocumentWorkflowID>

in

<DocumentWorkflowID>O</DocumentWorkflowID>
```
v
```
<edp:DocumentWorkflowID>I</edp:DocumentWorkflowID>

in

<DocumentWorkflowID>I</DocumentWorkflowID>

```

**Comment by sonysunny12** [comment]
Sem spremenil xml datoteke kot navedeno ampak Doh Div mi zdaj pri direktnem uvozu javi ''Oddaja dokumenta vrste ''I'' za zavezance ni možna, KDVP pa mi ne uvozi....ne zgodi se nič...čeprav so zapisi v datoteki. ne gre direkten uvoz ne iz dokumenta samega...

**Comment by masbug** [comment]
Z "O" pa tudi ne deluje?

**Comment by sonysunny12** [comment]
Doh Div uvozi z opozorilom da je bil rok za prijavo 28.02. KDVP pa ne uvozi sploh, ne z I, ne z O...

**Comment by sonysunny12** [comment]
pri Doh Div lahko označim samoprijavo s kljukico....to bo šlo skozi....problem je torej KDVP...

**Comment by masbug** [comment]
Čudno. Koliko pa je velika KDVP datoteka oz. so notri izpolnjeni <KDVPItem>...?
Za probat je še:
KDVP header je prazen oz. zgleda takole:
```
	<edp:Header>
		<edp:taxpayer/>
	</edp:Header>
```
zamenjaj tega s headerjem iz Doh-Div, da bo KDVP imel davčno številko. Mogoče bo pomagalo.

**Comment by sonysunny12** [comment]
Sorry....prazna je....tega potem ni kaj oddajat....za eno prejšnje leto je in sem zamešal...

**Comment by sonysunny12** [comment]
zdravo, zakaj mi pri oddaji Doh Div sedaj zahteva dokazilo o plačilu tujega davka, čeprav nisem označil da uveljavljam pravico do oprostitve? Ko sem oddajal februarja zase sem tudi imel v xml vnose pod tuji davek in mi ni zavračal z zahtevo po dokazilu o plačilu tujega davka. hvala! lp

**Comment by masbug** [comment]
Jaz dodam etoro.xlsx kot dokazilo in je to to. eToro avtomatsko odvede tuji davek.

**Comment by sonysunny12** [comment]
ok

**Comment by sonysunny12** [comment]
a je to kaj pomembno če javi, da je ena crypto pozicija skipped?
------------------------------------------------------------------------------
| eToro->eDavki | verzija 1.7.1 (3.8.2024)
------------------------------------------------------------------------------
output/Debug-2023.xlsx created
output/Doh-KDVP.xml created

Crypto: skipped (YFI)/YFI (2466098648)

output/D-IFI.xml created
output/Doh-Div.xml created
output/Dividende-info-2023.xlsx created

------------------------------------------------------------------------------------------------------------------------------------
Press any key to continue . . .


[etoro.xlsx](https://github.com/user-attachments/files/17628256/etoro.xlsx)

**Comment by masbug** [comment]
Crypto, ki ni CFD ali pa kaka druga oblika, ki pade pod D-IFI, ni obdavčena... To velja, če si fizična oseba....zato "skipped".

**Comment by sonysunny12** [comment]
Hvala!
