### ISSUE TITLE
Neobstoječi ključ v slovarju pozicij

### ISSUE THREAD

**Issue by damir-dezeljin** [masbug/etoro-edavki#5]
Ob zagonu skripte na mojem izvozu iz eTora se program prekine s sledečo napako:
```
$ python3 etoro_edavki.py -y 2020 ../eToroAccountStatement\ -\ 01-02-2020\ -\ 31-12-2020.xlsx
output/Debug-2020.xlsx created 
output/Doh-KDVP.xml created

Crypto: skipped Bitcoin (533286657,...,856205710)
...
output/D-IFI.xml created
Traceback (most recent call last):
  File "etoro_edavki.py", line 1018, in <module>
    main()
  File "etoro_edavki.py", line 846, in main
    open_pos = openPositions[position_id]
KeyError: 533286636
```

Naj takoj povem, da se nisem poglabljal za kaj gre. Zgolj predpostavka, morda kakšna pozicija, ki se prenese v letošnje leto 2021, ne vem.

**Vprašanja**:

- Morda ideja za kaj gre?
- Če gre za primer, ki sem ga navedel zgoraj, ali bi to bil fix:
  ```
  $ git diff
  diff --git a/etoro_edavki.py b/etoro_edavki.py
  old mode 100644
  new mode 100755
  index e1aed3e..86a2b43
  --- a/etoro_edavki.py
  +++ b/etoro_edavki.py
  @@ -1,4 +1,5 @@
  -#!/usr/bin/python
  +#!/usr/bin/env python3
  +# -*- coding: utf-8 -*-
   
   import urllib.request
   import sys
  @@ -838,6 +839,8 @@ def main():
               rate = get_exchange_rate(rates, date, ETORO_CURRENCY)
               amount_eur = str2float(xlsTransaction.amount) / rate
   
  +            if (openPositions.get(position_id) == None):
  +                print("POZOR: Ključa [position_id={0}] ni v slovarju [openPositions]".format(position_id))
  +                continue
               open_pos = openPositions[position_id]
               symbol = open_pos["symbol"]
  ```

**Comment by damir-dezeljin** [comment]
Vidim, da omenjen `position_id = 533286636` se pojavi 4x na listu _Transactions Report_ in sicer:
```
2020-03-11 01:53:43 | 0.   | Rollover Fee | Payment caused by dividend | 533286636 | 0,94 | 0,94 | 40090,32 | 0
2020-06-10 01:26:49 | 0,08 | Rollover Fee | Payment caused by dividend | 533286636 | 0,94 | 0,94 | 40124,9  | 0
2020-09-10 03:26:48 | 0,4. | Rollover Fee | Payment caused by dividend | 533286636 | 0,94 | 0,94 | 44179,26 | 0
2020-12-10 07:43:37 | 0,4. | Rollover Fee | Payment caused by dividend | 533286636 | 0,94 | 0,94 | 45717,36 | 0
```

**Comment by masbug** [comment]
Živjo,
pomoje je problem ta, da si delnico kupil že v prejšnjih letih, izpisek pa je samo za lansko obdobje in posledično manjka pod transactions nakup/prodaja te pozicije. Poskusi z izvozom vseh transakcij iz eTora.

Fix bi moral bit kritična napaka z opisom kaj naredit, ker sicer se lahko spregleda.

**Comment by masbug** [comment]
Je pomagal izvoz večjega obsega?

**Comment by damir-dezeljin** [comment]
Res je to bila težava. Sam sem sicer bil prepričan, da sem začel s trgovanjem 2. jan 2020, a se je izkazalo, da sem 31. dec 2019. Tako se opravičujem za nadlegovanje. Sem pa med poglabljanjem v težavo odkriv še kup drugih eToro specifik - npr. shortanje Tesle (in večine drugih) na eToru se smatra kot CFD in torej ne gre v kapitalske dobičke, temveč v IFI  - če prav razumem, druga obdavčitev.

Hvala in lp,
 Damir

**Comment by vincenthawke** [comment]
> npr. shortanje Tesle (in večine drugih) na eToru se smatra kot CFD in torej ne gre v kapitalske dobičke, temveč v IFI

Če bi kupil Teslo long, je to še vedno IFI, saj si kupil CFD tudi v tem primeru, ali ni tako? Vse kar prodaš na eToro se obdavči po IFI, vsaj tako sem jaz razumel.

**Comment by masbug** [comment]
@vincenthawke
Ne bo čisto držalo. Z delnicami na eToru lahko trguješ z "real" pozicijami, ampak to samo takrat kadar ne uporabiš leverage in kupiš long pozicijo. V ostalih primerih pa je nakup CFD. Kaj si kupil kot real in kaj CFD lahko vidiš v account statementu - stolpec "Is Real".
Vse real pozicije gredo pod Doh-KDVP, vse ostalo pod D-IFI. Zraven pa še zelo verjetno dobiš kako dividendo, zato je treba izpolnit še Doh-Div.
Še ena stvar, ki jo je potrebno pazit so kripto valute. eToro omogoča real in CFD. Real načeloma ni obdavčen, CFDji pa spet padejo pod D-IFI.

eToro samo na videz ne zaračunava provizij. V resnici pa vse lepo zapakirajo v "spread". Ker te eToro ne poveže direktno s stock marketom, nikoli dejansko ne veš ali kupiš kaj od eTora ali od dejanskega marketa. Imajo popoln nadzor nad delayi in cenami. Recimo v delčku sekunde lahko eToro na marketu za sebe kupi delnico po recimo 170 USD, po 0.5s pa jo proda tebi za 170.1USD, ker je cena na marketu zanihala. Sedaj pa to pomnoži s par miljonov transakcij in odkriješ poslovni model eTora. Seveda pa pri CFDjih še dodatno računajo provizije, ker ti posodijo delnice.
