### ISSUE TITLE
Razširitev tabele Naslovi_info.xlsx

### ISSUE THREAD

**Issue by damir-dezeljin** [masbug/etoro-edavki#6]
V tabelo Naslovi_info.xlsx bi rad dodal podatke za sledeče indekse: LMT, TXN, ULVR.L, VZ, HEN3.DE, MPW, BA, HL.L, TIP, MCHP, ITW, TLT, KR, AMAT, XLV, NXPI, BPY, GRMN, ATVI, CME, AGN. Datoteko sem že naredil, ne morem pa pushniti `feature/extend-companies-list-xlsx` brancha, da bi odprl pull request.

Drug predlog?
[Naslovi_info.xlsx](https://github.com/masbug/etoro-edavki/files/6046256/Naslovi_info.xlsx)

**Comment by masbug** [comment]
Naredi fork, pushni v svoj fork in potem ustvari pull request.
