### ISSUE TITLE
ModuleNotFoundError: No module named 'prettytable'

### ISSUE THREAD

**Issue by tomazb** [masbug/etoro-edavki#9]
Ubuntu 20 LTS

tomaz@ubnt-dsktp:~/etoro-edavki$ etoro-edavki 
Traceback (most recent call last):
  File "/home/tomaz/.local/bin/etoro-edavki", line 5, in <module>
    from etoro_edavki import main
  File "/home/tomaz/.local/lib/python3.8/site-packages/etoro_edavki.py", line 11, in <module>
    import prettytable
ModuleNotFoundError: No module named 'prettytable'

**Comment by tomazb** [comment]
Hmm, po kloniranju repozitorija in ukazu

pip3 install -r requirements.txt

Je bilo ok.

Samo "pip3 install --upgrade git+https://github.com/masbug/etoro-edavki.git" ni bilo dovolj.

**Comment by masbug** [comment]
Hvala za report, sem popravil setup.py (3c888d5).
